config:
  validation: true

build:
  maxIssues: 0
  excludeCorrectable: true
  weights:
    complexity: 2
    longMethod: 2
    largeClass: 1

comments:
  CommentOverPrivateFunction:
    active: false

complexity:
  LongParameterList:
    ignoreAnnotated: [ "Composable" ]
    functionThreshold: 5
    constructorThreshold: 6
  LargeClass:
    threshold: 200
  LongMethod:
    ignoreAnnotated: [ "Composable" ]


naming:
  FunctionNaming:
    ignoreAnnotated: [ "Composable" ]
  PackageNaming:
    packagePattern: '^[a-z]+([._]?[a-z0-9]+)*$'
    excludes: [ "**_**" ]

style:
  MagicNumber:
    ignoreNumbers: [ "-1", "0", "0.5", "1", "1.5", "2", ]
  WildcardImport:
    active: false
  ReturnCount:
    excludeGuardClauses: true
    max: 5
  LoopWithTooManyJumpStatements:
    maxJumpCount: 2


formatting:
  PackageName:
    active: false
  NoWildcardImports:
    active: false
  MaxLineLength:
    maxLineLength: 120


exceptions:
  TooGenericExceptionCaught:
    active: false